# Generated by Django 2.0.6 on 2018-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
