# Generated by Django 2.0.7 on 2018-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20180723_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
