# Generated by Django 2.0.7 on 2018-07-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20180723_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
