# Generated by Django 2.0.7 on 2018-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_auto_20180723_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identified',
            field=models.BooleanField(default=False),
        ),
    ]
