# Generated by Django 2.0.7 on 2018-07-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0010_auto_20180723_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
