# Generated by Django 2.0.7 on 2018-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0012_auto_20180724_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prof_answered',
            field=models.BooleanField(default=False),
        ),
    ]
